"""Add employee fields to users

Revision ID: 6fdaf7e3a9ec
Revises: c23215029a05
Create Date: 2026-07-07 14:25:49.411577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdaf7e3a9ec'
down_revision: Union[str, Sequence[str], None] = 'c23215029a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('joining_date', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'joining_date')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'employee_code')
    # ### end Alembic commands ###
