"""create_settings_table

Revision ID: bc64657860a9
Revises: 9848e867f4e1
Create Date: 2026-07-31 10:47:52.234805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc64657860a9'
down_revision: Union[str, Sequence[str], None] = '9848e867f4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_email', sa.String(length=200), nullable=True),
    sa.Column('company_phone', sa.String(length=30), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('date_format', sa.String(length=30), nullable=True),
    sa.Column('theme', sa.String(length=30), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('browser_notifications', sa.Boolean(), nullable=True),
    sa.Column('task_reminders', sa.Boolean(), nullable=True),
    sa.Column('weekly_reports', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
